apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: 942788320122.dkr.ecr.ap-south-1.amazonaws.com/nani/python:latest
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          value: "postgresql://user:password@postgres-service:5432/mydatabase"
        - name: REDIS_HOST
          value: "redis-service"
        resources:
          requests:
            cpu: "250m"      # Request 250 millicores (0.25 CPU)
            memory: "256Mi"  # Request 256MB of memory
          limits:
            cpu: "500m"      # Limit to 500 millicores (0.5 CPU)
            memory: "512Mi"  # Limit to 512MB of memory

---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
